create database SUPERDuAn1
GO
use SUPERDuAn1
GO
CREATE TABLE Khach_Hang
(
  HoTen NVARCHAR(50) NOT NULL,
  SoDienThoai NVARCHAR(10) NOT NULL,
  Email NVARCHAR(50) NOT NULL,
  DiaChi NVARCHAR(50) NOT NULL,
  MaKH NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaKH)
);

CREATE TABLE Nhan_Vien
(
  MaNV NVARCHAR(10) NOT NULL,
  TenNV NVARCHAR(50) NOT NULL,
  GioiTinh NVARCHAR(10) NOT NULL,
  NgaySinh DATE NOT NULL,
  VaiTro NVARCHAR(50) NOT NULL,
  Email NVARCHAR(50) NOT NULL,
  Hinh NVARCHAR(50) NOT NULL,
  MatKhau NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaNV)
);

CREATE TABLE Lich_Lam_Viec
(
  ID INT NOT NULL,
  TenNV NVARCHAR(50) NOT NULL,
  NgayLamViec DATE NOT NULL,
  CaLamViec INT NOT NULL,
  ThoiGianLamViec NVARCHAR(50) NOT NULL,
  MaNV NVARCHAR(10) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (MaNV) REFERENCES Nhan_Vien(MaNV)
);

CREATE TABLE Loai_SanPham
(
  Maloai NVARCHAR(10) NOT NULL,
  TenLoai NVARCHAR(50) NOT NULL,
  PRIMARY KEY (Maloai)
);

CREATE TABLE Kho
(
  MaKho NVARCHAR(10) NOT NULL,
  TenKho NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaKho)
);

CREATE TABLE Phieu_Xuat
(
  MaSoPhieu NVARCHAR(10) NOT NULL,
  TenSP NVARCHAR(50) NOT NULL,
  NgayTao DATE NOT NULL,
  MaKho NVARCHAR(10) NOT NULL,
  MaNV NVARCHAR(10) NOT NULL,
  PRIMARY KEY (MaSoPhieu),
  FOREIGN KEY (MaKho) REFERENCES Kho(MaKho),
  FOREIGN KEY (MaNV) REFERENCES Nhan_Vien(MaNV)
);

CREATE TABLE Phieu_Nhap
(
  MaSoPhieu NVARCHAR(10) NOT NULL,
  TenSP NVARCHAR(50) NOT NULL,
  NgayTao DATE NOT NULL,
  MaKho NVARCHAR(10) NOT NULL,
  MaNV NVARCHAR(10) NOT NULL,
  PRIMARY KEY (MaSoPhieu),
  FOREIGN KEY (MaKho) REFERENCES Kho(MaKho),
  FOREIGN KEY (MaNV) REFERENCES Nhan_Vien(MaNV)
);

CREATE TABLE San_Pham
(
  MaSP NVARCHAR(10) NOT NULL,
  TenSP NVARCHAR(50) NOT NULL,
  SoLuong INT NOT NULL,
  Gia FLOAT NOT NULL,
  NgayNhapHang DATE NOT NULL,
  TrangThai NVARCHAR(50) NOT NULL,
  Maloai NVARCHAR(10) NOT NULL,
  MaKho NVARCHAR(10) NOT NULL,
  HinhAnh NVARCHAR(20) NOT NULL,
  PRIMARY KEY (MaSP),
  FOREIGN KEY (Maloai) REFERENCES Loai_SanPham(Maloai),
  FOREIGN KEY (MaKho) REFERENCES Kho(MaKho)
);

CREATE TABLE Hoa_Don
(
  MaDH NVARCHAR(10) NOT NULL,
  TenKH NVARCHAR(50) NOT NULL,
  NgayDatHang DATE NOT NULL,
  SoDienThoai NVARCHAR(10) NOT NULL,
  DiaChi NVARCHAR(50) NOT NULL,
  ThanhTien FLOAT NOT NULL,
  MaNV NVARCHAR(10) NOT NULL,
  MaKH NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaDH),
  FOREIGN KEY (MaNV) REFERENCES Nhan_Vien(MaNV),
  FOREIGN KEY (MaKH) REFERENCES Khach_Hang(MaKH)
);

CREATE TABLE ChiTietHD
(
  TenSP NVARCHAR(50) NOT NULL,
  SoLuongDC INT  NOT NULL,
  Gia  FLOAT NOT NULL,
  MaDH NVARCHAR(10) NOT NULL,
  MaSP NVARCHAR(10) NOT NULL,
  PRIMARY KEY (MaDH, MaSP),
  FOREIGN KEY (MaDH) REFERENCES Hoa_Don(MaDH)
);

CREATE TABLE ChiTiet_Xuat
(
  ThanhTien FLOAT NOT NULL,
  TrangThai NVARCHAR(50) NOT NULL,
  MaSoPhieu NVARCHAR(10) NOT NULL,
  MaSP NVARCHAR(10) NOT NULL,
  PRIMARY KEY (MaSoPhieu, MaSP),
  FOREIGN KEY (MaSoPhieu) REFERENCES Phieu_Xuat(MaSoPhieu),
  FOREIGN KEY (MaSP) REFERENCES San_Pham(MaSP)
);

CREATE TABLE ChiTiet_Nhap
(
  ThanhTien FLOAT NOT NULL,
  TrangThai NVARCHAR(50) NOT NULL,
  MaSoPhieu NVARCHAR(10) NOT NULL,
  MaSP NVARCHAR(10) NOT NULL,
  PRIMARY KEY (MaSoPhieu, MaSP),
  FOREIGN KEY (MaSoPhieu) REFERENCES Phieu_Nhap(MaSoPhieu),
  FOREIGN KEY (MaSP) REFERENCES San_Pham(MaSP)
);